version: "3.7"
services:

    dash:
        container_name: "dash"
        build:
            context: ./dockerfiles/dockerfile_dash
        restart: always
        ports:
            - 8050:8050
            - "5001:5001" # app(debug) port
            - "3000:3000" # remote debugger attach port
        volumes:
            - ./Storage/dash:/app
            - ./Storage/q_pack:/q_pack
        environment: 
            - FLASK_DEBUG=1
            - FLASK_APP=app.py
            - FLASK_ENV=development
        # command:
        #     python app.py --host=0.0.0.0"


# volumes:
#     pg_data:
#         external: false
#         name: pg_data
#     pg_data_airflow:
#         external: false
#         name: pg_data_airflow
#     redis:
#         external: false
#         name: redis


        # docker-compose up -d --scale worker=5