# dbHost="postgres_secmaster"
# dbUser="postgres"
# dbPWD="posgres349"
# dbName="securities_master"

# dbHost="db.equibrant.com"
dbHost="34.74.230.164"
dbUser="smd"
dbPWD="p4ssw0rd"
dbName="securities_master"
